# Generated by Django 4.1 on 2025-04-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = []
