# Generated by Django 4.1 on 2025-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0002_auto_20250409_0403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(to="tracker_app.user"),
        ),
    ]
